# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb25f404681f05de45b38988fcb60a222ccb854ed7d349efb8941fc68987611cddecc1a5644c4323e1ae36eceff41a150af4721ad975b6691e760fb8f745fdcb

test:
  secret_key_base: dc8584eb04c54f62c84d96e8104b7e4fe5a2c7fe739699e5f06e1170e62fe274d823e7ee3d8624a8af669b61ca867205609db4b003a0ab8002155759f2adeb92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
